"""Core utilities for the CI/CD diagnosis agent project."""

from .core.actions import (
    ACTION_TO_INDEX,
    EVIDENCE_ACTIONS,
    FINAL_ACTION,
    INDEX_TO_ACTION,
    TEST_TIME_ONLY_TOOLS,
    TRAINING_ACTIONS,
)
from .core.dataset import CICDDiagnosisDataset, CaseBundle, DatasetPaths, DatasetValidationError, load_dataset
from .training.bc import (
    BCExample,
    BehaviorCloningDatasetBuilder,
    BehaviorCloningPolicy,
    DatasetSplit,
    SoftmaxPolicyModel,
    StateVectorizer,
    TrainResult,
    train_behavior_cloning_policy,
)
from .core.env import CICDDiagnosisEnv, RewardConfig
from .core.final_answer import GeneratedFinalAnswer, TemplateFinalAnswerGenerator
from .runtime.inference import DiagnosisRunResult, render_final_answer, run_diagnosis, run_diagnosis_from_path, save_diagnosis_result
from .training.dpo import (
    DEFAULT_DPO_INIT_POLICY_PATH,
    DEFAULT_DPO_PREFERENCES_PATH,
    DPODatasetBuildSummary,
    DPOPolicy,
    DPOPreferenceDatasetBuilder,
    DPOPreferenceExample,
    DPOTrainConfig,
    DPOTrainResult,
    evaluate_dpo_preferences,
    train_dpo_policy,
)
from .runtime.web_aug import (
    DuckDuckGoSearchClient,
    SearchUnavailableError,
    StaticSearchClient,
    WebAugmentationResult,
    WebAugmentedAnswer,
    WebSearchClient,
    WebSearchHit,
    augment_diagnosis_from_result_path,
    augment_diagnosis_result,
    render_web_augmented_answer,
    run_and_augment_diagnosis,
    save_web_augmentation_result,
)
from .training.eval import (
    AggregateEvaluationResult,
    CaseEvaluationResult,
    ComparisonReport,
    PolicyEvaluationReport,
    compare_policies,
    evaluate_policy,
    load_policy,
    rollout_policy_on_case,
    summarize_case_results,
    write_comparison_report,
)
from .training.rl import (
    DEFAULT_BC_POLICY_PATH,
    DQNQNetwork,
    EvaluationResult,
    ReplayBuffer,
    ReplayTransition,
    RLTrainConfig,
    RLTrainResult,
    RLFineTunedPolicy,
    evaluate_rl_policy,
    load_bc_policy_or_raise,
    split_rl_cases,
    train_rl_fine_tuning,
)
from .core.tools import DeterministicToolExecutor, ToolExecutionError, ToolResult, UnknownToolError

__all__ = [
    "ACTION_TO_INDEX",
    "EVIDENCE_ACTIONS",
    "FINAL_ACTION",
    "INDEX_TO_ACTION",
    "TEST_TIME_ONLY_TOOLS",
    "TRAINING_ACTIONS",
    "CICDDiagnosisDataset",
    "CaseBundle",
    "DatasetPaths",
    "DatasetValidationError",
    "BCExample",
    "BehaviorCloningDatasetBuilder",
    "BehaviorCloningPolicy",
    "DatasetSplit",
    "SoftmaxPolicyModel",
    "StateVectorizer",
    "TrainResult",
    "train_behavior_cloning_policy",
    "CICDDiagnosisEnv",
    "RewardConfig",
    "GeneratedFinalAnswer",
    "TemplateFinalAnswerGenerator",
    "DiagnosisRunResult",
    "render_final_answer",
    "run_diagnosis",
    "run_diagnosis_from_path",
    "save_diagnosis_result",
    "DEFAULT_DPO_INIT_POLICY_PATH",
    "DEFAULT_DPO_PREFERENCES_PATH",
    "DPODatasetBuildSummary",
    "DPOPolicy",
    "DPOPreferenceDatasetBuilder",
    "DPOPreferenceExample",
    "DPOTrainConfig",
    "DPOTrainResult",
    "evaluate_dpo_preferences",
    "train_dpo_policy",
    "DuckDuckGoSearchClient",
    "SearchUnavailableError",
    "StaticSearchClient",
    "WebAugmentationResult",
    "WebAugmentedAnswer",
    "WebSearchClient",
    "WebSearchHit",
    "augment_diagnosis_from_result_path",
    "augment_diagnosis_result",
    "render_web_augmented_answer",
    "run_and_augment_diagnosis",
    "save_web_augmentation_result",
    "AggregateEvaluationResult",
    "CaseEvaluationResult",
    "ComparisonReport",
    "PolicyEvaluationReport",
    "compare_policies",
    "evaluate_policy",
    "load_policy",
    "rollout_policy_on_case",
    "summarize_case_results",
    "write_comparison_report",
    "DEFAULT_BC_POLICY_PATH",
    "DQNQNetwork",
    "EvaluationResult",
    "ReplayBuffer",
    "ReplayTransition",
    "RLTrainConfig",
    "RLTrainResult",
    "RLFineTunedPolicy",
    "evaluate_rl_policy",
    "load_bc_policy_or_raise",
    "split_rl_cases",
    "train_rl_fine_tuning",
    "DeterministicToolExecutor",
    "ToolExecutionError",
    "ToolResult",
    "UnknownToolError",
    "load_dataset",
]
